name: Deploy Infrastructure Github Runner
  
on:
  workflow_dispatch:
jobs:
  terraform-apply:
    name: Terraform deploy
    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is running on ${{ runner.os }} runner hosted by Github"
      - run: echo "This workflow is running on branch ${{ github.ref }}"
      - name: Repository clone
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform Apply DNS
        run: terraform apply -target="null_resource.cmd" -auto-approve
      - name: Terraform Apply Infrastructure
        run: terraform apply -auto-approve