name: Plan Infrastructure Github Runner
  
on:
  workflow_dispatch:
    inputs:
      host:
        description: "Choose on running on ec2 or eks"
        required: true
        default: "ec2"
      state:
        description: "The S3 bucket to save state(Leave empty if no s3 state)"
        required: true
        default: ""
jobs:
  terraform-apply:
    name: Terraform plan
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
    steps:
      - run: echo "This job is running on ${{ runner.os }} runner hosted by Github"
      - name: Repository clone EC2
        if: github.event.inputs.host == 'ec2'
        uses: actions/checkout@v4
      - name: Repository clone EKS
        if: github.event.inputs.host == 'eks'
        uses: actions/checkout@v4
        with:
          ref: "eks"
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Apply DNS
        run: terraform apply -target="null_resource.cmd" -auto-approve
      - name: Terraform Plan Infrastructure
        if: github.event.inputs.state == ""
        run: terraform plan
      - name: Terraform Plan Infrastructure with S3 state
        if: github.event.inputs.state != ""
        run: terraform plan -state-out=s3://{github.event.inputs.state}
        